### PR TITLE
Initial commit of app_units contents

### PR DESCRIPTION
**Pull request by frewsxcv**
https://github.com/servo/servo/issues/8012

### CODE REVIEW

**Comment by jdm** [comment]
I lack permissions to modify settings in this repo; do you have the ability to add teams?

**Comment by frewsxcv** [comment]
The only team I can add is 'developers'. I added you as an admin individually though. Maybe you can fix it?

**Comment by Ms2ger** [comment]
Blocked on @erickt.

**Comment by Ms2ger** [comment]
Also needs a `salt servo-master state.highstate`; should be all set then.

**Comment by frewsxcv** [comment]
https://github.com/serde-rs/aster/issues/42

**Comment by Manishearth** [comment]
This now compiles since serde is optional

**Comment by erickt** [comment]
@Ms2ger: Finally finished updating aster. I had to make some some breaking changes though to account for the new `VariantData` support.

**Comment by Manishearth** [comment]
@glennw could you publish this crate and delete the in-tree one? (also, add `servo/cargo-publish` as an owner)

**Comment by frewsxcv** [comment]
@Manishearth this crate is already published. i already opened a PR in servo https://github.com/servo/servo/pull/8025

**Comment by Manishearth** [comment]
as in, publish the current version

**Comment by glennw** [comment]
@Manishearth I've added servo/cargo-publish as an owner and opened https://github.com/servo/app_units/pull/2 (to update the version so it can be published).

**Pull request merged**
