### PR TITLE
Round number before convert to i32

### PR DESCRIPTION
**Pull request by upsuper**

### CODE REVIEW

**Comment by emilio** [comment]
Looks good to me with a version bump.

**Comment by upsuper** [comment]
Do we need a breaking bump or a patch bump?

**Comment by mbrubeck** [comment]
It's not an API change, but it is an observable behavior change. If we consider it a bug fix (i.e. the previous behavior was incorrect) then it can be a patch bump; otherwise it's a breaking bump.

I think this one could be argued either way.  Personally I don't foresee any downstream consumers of this crate wanting or needing to change their code in order to upgrade, so I would consider this a non-breaking bug fix.

**Comment by upsuper** [comment]
Added a patch bump.

**Comment by nox** [comment]
@emilio @mbrubeck This broke tests in Servo and I have no idea why that change was needed.

**Comment by nox** [comment]
https://github.com/servo/servo/pull/15479#issuecomment-278851659

**Comment by upsuper** [comment]
There are also several places Servo side should fix to get the rounding right. Servo currently does flooring rather than rounding, which causes rounding issues in Gecko's style system tests.

**Comment by upsuper** [comment]
That said, you can probably leave app_units unchanged in Servo for now, and I can do the rest of the fix together with integrating this version bump.

**Comment by nox** [comment]
@upsuper The app_units bump is blocking the serde bump. So if "for now" is a very short period, yes I can do that; otherwise I can't.

**Comment by upsuper** [comment]
@nox you can probably specify app_units = 0.3.0 for now?

**Comment by nox** [comment]
@upsuper 0.3.0 isn't published yet because I want to test the serde bump before landing it, and even if I did; it would include your own change.

**Comment by upsuper** [comment]
It seems 0.3.0 was published: https://crates.io/crates/app_units/0.3.0

**Comment by nox** [comment]
Err right. Off-by-one error.

@upsuper The serde bump needs to be 0.4.0, so it doesn't change the problem, if I do manage to test the serde bump by changing my own PR to be based on 0.3.0, we won't be able to land it, so that app_units bump is urgent.

**Comment by upsuper** [comment]
Oh, so what you want to do is to bump serde to 0.9.x?

OK, let me have a look at fixing Servo side rounding issue and bump app_units first.

**Comment by nox** [comment]
@upsuper I want app_unit's most recent version to land in servo so that the serde bump PR contains only that, and not unrelated other bumps that can cause test issues (like we just saw). Thanks for working on it, feel free to reuse my commit with the already-changed expectations.

**Comment by upsuper** [comment]
So you're going to land with the changed expectations? Or should I try to fix them and bump app_units to 0.3.1 first?

**Comment by nox** [comment]
I have no idea what you mean, so let's make it easy: forget anything we said and please make https://github.com/servo/servo/pull/15479#issuecomment-278918005 land.

**Pull request merged**
